variables:
  phpVersion: 7.2

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

resources: 
    containers: 
    - container: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
      env:
        discovery.type: single-node
      ports:
      - 9200:9200
jobs:
- job: Lint
  displayName: Lint
  steps:
  - template: templates/magento-auth.yml
  - template: templates/composer-install.yml
  - script: composer run-script lint
    displayName: Lint
- job: Unit_Test
  displayName: Unit Test
  steps:
  - template: templates/magento-auth.yml
  - template: templates/composer-install.yml
  - script: composer run-script unit-test
    displayName: Unit Test
- job: Integration_Test
  displayName: Integration Test
  strategy:
    matrix:
      php72_magento2.3:
        phpVersion: 7.2
        magentoTag: 2.3
      php73_magento2.3:
        phpVersion: 7.3
        magentoTag: 2.3
      php73_magento2.4:
        phpVersion: 7.3
        magentoTag: 2.4
      php74_magento2.4:
        phpVersion: 7.4
        magentoTag: 2.4
  services:
    elasticsearch: elasticsearch
  steps:
  - template: templates/setup-php.yml
  - script: bash ./ci/scripts/wait-for-elasticsearch.sh http://localhost:9200/_cat/health?h=status
    displayName: Waiting for Elasticsearch
  - template: templates/magento-auth.yml
  - template: templates/integration-setup.yml
  - script: |
      cd $(pwd)/../magento2/dev/tests/integration
      ../../../vendor/bin/phpunit --testsuite "Graycore_Magento2Cors"
    displayName: Run Integration Tests
